articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('article-list/', views.ArticleListView.as_view(), name='article_list'),
    path('my-articles-list/', views.MyArticleListlView.as_view(), name='my_articles'),
    path('category/<slug:cat_slug>/', views.ArticleListView.as_view(), name='category'),

    path('create-article/', views.ArticleCreateView.as_view(), name='create_article'),
    path('edit/<slug:slug>/', views.ArticleUpdateView.as_view(), name='edit_article'),
    path('delete/<slug:slug>/', views.ArticleDeleteView.as_view(), name='delete_article'),
    path('<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
]

myfinances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finances.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles')),
] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    path('registration/', views.UserCreateView.as_view(), name='registration'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('profile/', views.UserProfileView.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html', 
        extra_context={'title': 'Пароль успешно изменен!'}), name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html', 
        email_template_name='users/password_reset_email.html',
        extra_context={'title': 'Сброс пароля'}, 
        success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html',
        extra_context={'title': 'Сброс пароля'}), 
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

articles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.core.validators import MinLengthValidator
from transliterate import slugify
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(db_index=True, unique=True, verbose_name='Категория')
    slug = models.SlugField(max_length=100, unique=True, blank=True, verbose_name='slug')

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class PublishedArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=1)


class Article(models.Model):
    HIDDEN_STATUS = -1
    DRAFT_STATUS = 0
    PUBLISHED_STATUS = 1
    STATUS_CHOICES = (
        (HIDDEN_STATUS, 'Скрыто'),
        (DRAFT_STATUS, 'Черновик'),
        (PUBLISHED_STATUS, 'Опубликовано'),
    )
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, 
                               null=True, related_name='articles', verbose_name='Автор')
    title = models.CharField(max_length=200, verbose_name='Заголовок',
                             validators=[MinLengthValidator(5, message="Минимум 5 символов")])
    slug = models.SlugField(max_length=100, unique=True, verbose_name='Slug')
    content = models.TextField(verbose_name='Текст статьи') # Textarea.
    photo = models.ImageField(upload_to="photos/%Y/%m/", blank=True, null=True, verbose_name='Фото статьи')
    time_create = models.DateTimeField(auto_now=True, verbose_name='Время создания') # DateInput.
    time_update = models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, max_length=100, 
                                 related_name= 'articles', verbose_name='Категория')
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=DRAFT_STATUS, verbose_name='Статус')
    tags = TaggableManager(blank=True, verbose_name='Теги')

    objects = models.Manager()
    published = PublishedArticleManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ['-time_update']

    def get_absolute_url(self):
        return reverse('articles:article_detail', kwargs={"slug": self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    

articles/forms.py
from django import forms
from .models import Article


class ArticleCreateForm(forms.ModelForm):
    title = forms.CharField(min_length=5, label='Заголовок')
    class Meta:
        model = Article
        fields = ['title', 'content', 'photo', 'category', 'status', 'tags']

articles/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ArticleCreateForm
from .models import Article


class ArticleListView(ListView):
    extra_context = {'title': 'Все статьи'}
    template_name = 'articles/article_list.html'
    context_object_name = 'articles'
    paginate_by = 5

    def get_queryset(self):
        return Article.published.all()


class ArticleDetailView(DetailView):
    template_name = 'articles/article_detail.html'
    context_object_name = 'article'

    def get_object(self, queryset = None):
        return Article.objects.get(slug=self.kwargs.get(self.slug_url_kwarg, None))


class ArticleCreateView(LoginRequiredMixin, CreateView):
    form_class = ArticleCreateForm
    template_name = 'articles/create_article.html'
    extra_context = {'title': 'Создание статьи'}

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    template_name = 'articles/edit_article.html'
    extra_context = {'title': 'Редактирование статьи'}
    fields = ["title", "content", "photo", "category", "status", "tags"]


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    template_name = "articles/delete_article.html"
    extra_context = {'title': 'Удаление статьи'}
    success_url = reverse_lazy("articles:article_list")


class MyArticleListlView(LoginRequiredMixin, ListView):
    extra_context = {'title': 'Мои статьи'}
    template_name = 'articles/article_list.html'
    context_object_name = 'articles'
    paginate_by = 5

    def get_queryset(self):
        return Article.objects.filter(author = self.request.user)

articles/templates/articles/article_detail.html
{% extends "base.html" %}


{% block head_title %}
<title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    <div class="row">
        <div class="col-12">
            {% include "articles/includes/category_and_tags.html" %}
            <h1 class='text-center mb-3 mt-2'>{{ article.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <p>{{ article.content|linebreaks }}</p>
        </div>
    </div>
</div>
</section>
{% endblock content %}

articles/templates/articles/article_list.html
{% extends "base.html" %}


{% block head_title %}
    <title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    {% comment %} Начало списка статей {% endcomment %}
    <div class="row mb-5">
        <div class="col-12">
            {% if not articles %}
                <h2 class="text-center">Вы не создали ни одной статьи</h2>
            {% else %}
                {% for article in articles %}
                    {% include "articles/includes/category_and_tags.html" %}
                    
                    <h4 class="mt-2">{{ article.title|truncatewords:15 }}</h4>

                    <p>{{ article.content|truncatewords:40 }}</p>

                    <a href="{{ article.get_absolute_url }}" class="a-underscore btn btn-primary mt-1">
                        Читать статью
                    </a>

                    {% if article.author.username == user.username %}
                        <a href="{% url "articles:edit_article" article.slug %}" class="a-underscore btn btn-secondary mt-1">
                            Редактировать
                        </a>
                        <a href="{% url "articles:delete_article" article.slug %}" class="a-underscore btn btn-danger mt-1">
                            Удалить статью
                        </a>
                    {% endif %}

                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}
            {% endif %}
            
        </div>
    </div>
    {% comment %} Конец списка статей {% endcomment %}

    {% if page_obj.has_other_pages %}
        <div class="row">
            <div class="col-12">
                {% comment %} Начало пагинации {% endcomment %}
                <nav aria-label="Навигация по страницам">
                    <ul class="pagination justify-content-center">
                        {% if page_obj.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Предыдущая">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.number|add:"-1" }}</a>
                        </li>
                        {% endif %}
                        
                        <li class="page-item disabled"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.number|add:"1" }}</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Следующая">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        <li><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a></li>
                        {% endif %}
                    </ul>
                </nav>
                {% comment %} Начало пагинации {% endcomment %}
            </div>
        </div>
    {% endif %}
</div>
</section>
{% endblock content %}

articles/templates/articles/create_article.html
{% extends "base.html" %}


{% block head_title %}
<title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <div class="create-article">
            <form action="" method="post" enctype="multipart/form-data">
                {% include "includes/post_form.html" %}
            </div>
                <button class="btn btn-primary mt-2" type="submit">Создать статью</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock content %}

articles/templates/articles/delete_article.html
{% extends "base.html" %}


{% block head_title %}
<title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <form action="" method="post">
                {% csrf_token %}
                <button class="btn btn-danger mt-2" type="submit">Удалить статью</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock content %}

articles/templates/articles/edit_article.html
{% extends "base.html" %}


{% block head_title %}
<title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <div class="create-article">
            <form action="" method="post" enctype="multipart/form-data">
                {% include "includes/post_form.html" %}
            </div>
                <button class="btn btn-primary mt-2" type="submit">Сохранить изменения</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock content %}