myfinances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finances.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles')),
] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    path('registration/', views.UserCreateView.as_view(), name='registration'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('profile/', views.UserProfileView.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html', 
        extra_context={'title': 'Пароль успешно изменен!'}), name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html', 
        email_template_name='users/password_reset_email.html',
        extra_context={'title': 'Сброс пароля'}, 
        success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html',
        extra_context={'title': 'Сброс пароля'}), 
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

users/models.py
from django.db import models


class UserFinance(models.Model):
    username = models.CharField(max_length=100, primary_key=True, verbose_name='Логин')
    name = models.CharField(max_length=20, blank=True, verbose_name='Имя')
    surname = models.CharField(max_length=20, blank=True, verbose_name='Фамилия')
    total_amount = models.FloatField(default=0, verbose_name='Общая сумма')

    def add(self, other):
        if isinstance(other, (int, float)):
            self.total_amount += other
        else:
            return NotImplemented

    def sub(self, other):
        if isinstance(other, (int, float)):
            self.total_amount -= other
        else:
            return NotImplemented


# class OperationHistory(models.Model):
#     operation_name = models.CharField(max_length=255)



# class PiggyBank(models.Model):
#     pass

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model


class UserCreateForm(UserCreationForm):
    username = forms.CharField(label='Логин*')
    password1 = forms.CharField(label='Пароль*', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повтор пароля*', widget=forms.PasswordInput())
    email = forms.EmailField(label='E-mail*')
    class Meta:
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Логин')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput())

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class UserProfileForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин')
    email = forms.CharField(disabled=True, label='E-mail')
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput())
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput())
    new_password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput())

users/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserCreateForm, UserLoginForm, UserProfileForm, UserPasswordChangeForm

from django.contrib.auth import get_user_model, logout
from django.urls import reverse_lazy, reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect


class UserProfileView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль'}
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserCreateView(CreateView):
    form_class = UserCreateForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    extra_context = {'title': 'Регистрация'}


class UserLoginView(LoginView):
    form_class = UserLoginForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}
    success_url = reverse_lazy('users:profile')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    extra_context = {'title': 'Изменение пароля'}
    success_url = reverse_lazy('users:password_change_done')

users/templates/users/login.html
{% extends "base.html" %}

{% block head_title %}
    <title>{{ title }}</title>
{% endblock head_title %}

{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% include "includes/post_form.html" %}
                <button class="btn btn-primary mt-3" type="submit">Войти</button>
            </form>
            <div class="line1"></div>
            <a href="{% url "users:password_reset" %}">Забыли пароль?</a>
        </div>
    </div>
</div>
</section>
{% endblock content %}

users/templates/users/password_change_done.html
{% extends "base.html" %}


{% block head_title %}
<title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}
</div>
</section>
{% endblock content %}

users/templates/users/password_change_form.html
{% extends "base.html" %}

{% block head_title %}<title>{{ title }}</title>{% endblock head_title %}

{% block content %}
<h1>{{ title }}</h1>
<form action="" method="post">
    {% csrf_token %}
    {% for f in form %}
        <p>{{ f.label }} {{ f }}</p>
    {% endfor %}
    <button type="submit">Изменить пароль</button>
</form>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <a href="{% url "users:login" %}" class="btn btn-primary">Войти</a>
        </div>
    </div>
</div>
</section>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <form action="" method="post">
                {% include "includes/post_form.html" %}
                <button class="btn btn-primary mt-3" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}


{% block head_title %}
    <title>Восстановление пароля</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            На указанную почту отправлены инструкции по сбросу пароля.
        </div>
    </div>
</div>
</section>
{% endblock content %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}


{% block head_title %}
    <title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <form action="" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary mt-1" type="submit">Сбросить пароль</button>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}


{% block head_title %}
<title>{{ title }}</title>
{% endblock head_title %}


{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <form action="" method="post">
                {% include "includes/post_form.html" %}
                <button class="btn btn-primary mt-2" type="submit">Изменить данные</button>
            </form>
            <div class="line1"></div>
            <a href="{% url 'users:password_change' %}">Изменить пароль</a>
        </div>
    </div>
</div>
</section>
{% endblock content %}

users/templates/users/registration.html
{% extends "base.html" %}

{% block head_title %}
<title>{{ title }}</title>
{% endblock head_title %}

{% block content %}
<section>
<div class="container">
    {% include "includes/header.html" %}

    <div class="row">
        <div class="col-12 text-center">
            <form action="" method="post">
                {% include "includes/post_form.html" %}
                <button class="btn btn-primary mt-2" type="submit">Зарегистироваться</button>
            </form>
            <div class="line1"></div>
            <a href="{% url "users:login" %}">Уже есть аккаунт?</a>
        </div>
    </div>
</div>
</section>
{% endblock content %}