articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [
    path('article-list/', views.ArticleListView.as_view(), name='article_list'),
    path('my-articles-list/', views.MyArticleListlView.as_view(), name='my_articles'),
    path('category/<slug:cat_slug>/', views.ArticleListView.as_view(), name='category'),

    path('create-article/', views.ArticleCreateView.as_view(), name='create_article'),
    path('edit/<slug:slug>/', views.ArticleUpdateView.as_view(), name='edit_article'),
    path('delete/<slug:slug>/', views.ArticleDeleteView.as_view(), name='delete_article'),
    path('<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
]

myfinances/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finances.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('articles/', include('articles.urls', namespace='articles')),
] 

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    path('registration/', views.UserCreateView.as_view(), name='registration'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),

    path('profile/', views.UserProfileView.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html', 
        extra_context={'title': 'Пароль успешно изменен!'}), name='password_change_done'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html', 
        email_template_name='users/password_reset_email.html',
        extra_context={'title': 'Сброс пароля'}, 
        success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html',
        extra_context={'title': 'Сброс пароля'}), 
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name="users/password_reset_confirm.html",
        success_url=reverse_lazy('users:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name="users/password_reset_complete.html"), name='password_reset_complete'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head_title %}{% endblock head_title %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href=" {% static 'img/favicon.svg' %}" sizes="any">
</head>
<body>
{% comment %} Начало авигационной панели {% endcomment %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{%static 'img/favicon.ico' %}" alt="Логотип"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "about" %}">О сайте</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "articles:article_list" %}">Все статьи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Калькулятор</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Профиль
                    </a>
                    <ul class="dropdown-menu bg-dark">
                        <li><a class="dropdown-item" href="{% url "articles:create_article" %}">Создать статью</a></li>
                        <li><a class="dropdown-item" href="{% url "articles:my_articles" %}">Мои статьи</a></li>
                        <li><hr class="dropdown-divider bg-white"></li>

                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url "users:profile" %}">{{ user.username }}</a></li>
                            <li><a class="dropdown-item" href="{% url "users:logout" %}">Выйти</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url "users:login" %}">Вход</a></li>
                            <li><a class="dropdown-item" href="{% url "users:registration" %}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% comment %} Конец авигационной панели {% endcomment %}

{% block content %}{% endblock content %}

{% comment %} Начало футера {% endcomment %}
<footer class="text-bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-6 mb-3">
                Далеко-далеко за словесными горами в стране гласных и согласных живут, рыбные тексты. Текста буквоград грамматики, путь скатился обеспечивает рыбными подпоясал прямо запятых речью lorem правилами послушавшись рыбного щеке?
            </div>

            <div class="col-lg-4 col-sm-6 mb-3">
                Далеко-далеко за словесными, горами в стране гласных и согласных живут рыбные тексты. Залетают если гор дорогу толку назад образ жизни первую повстречался?
            </div>

            <div class="col-lg-4 col-sm-6 mb-3">
                Далеко-далеко, за словесными горами в стране гласных и согласных живут рыбные тексты. Пустился маленький семь по всей подзаголовок жаренные живет, проектах залетают рот!
            </div>
        </div>
    </div>
</footer>
{% comment %} Конец футера {% endcomment %}

<script type="text/javascript" src={% static "js/bootstrap.bundle.min.js" %}></script>
</body>
</html>

templates/old_base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head_title %}{% endblock head_title %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href=" {% static 'img/favicon.svg' %}" sizes="any">
</head>
<body>
{% comment %} Начало авигационной панели {% endcomment %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{%static 'img/favicon.ico' %}" alt="Логотип"></a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url "about" %}">О сайте</a>
                <a class="nav-link" href="{% url "articles:article_list" %}">Все статьи</a>
                <a class="nav-link" href="{% url "articles:my_articles" %}">Мои статьи</a>
                <a class="nav-link" href="{% url "articles:create_article" %}">Создать статью</a>
                <a class="nav-link" href="#">Калькулятор</a>
            </div>
        </div>

        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url "users:profile" %}">{{ user.username }}</a>
                <a class="nav-link" href="{% url "users:logout" %}">Выйти</a>
            {% else %}
                <a class="nav-link text-right" href="{% url "users:login" %}">Вход</a>
                <a class="nav-link text-right" href="{% url "users:registration" %}">Регистрация</a>
            {% endif %}
        </div>
    </div>
</nav>
{% comment %} Конец авигационной панели {% endcomment %}

{% block content %}{% endblock content %}

{% comment %} Начало футера {% endcomment %}
<footer class="text-bg-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-sm-6 mb-3">
                Тут могла быть ваша реклама
            </div>

            <div class="col-lg-4 col-sm-6 mb-3">
                Далеко-далеко за словесными, горами в стране гласных и согласных живут рыбные тексты. Залетают если гор дорогу толку назад образ жизни первую повстречался?
            </div>

            <div class="col-lg-4 col-sm-6 mb-3">
                Далеко-далеко, за словесными горами в стране гласных и согласных живут рыбные тексты. Пустился маленький семь по всей подзаголовок жаренные живет, проектах залетают рот!
            </div>
        </div>
    </div>
</footer>
{% comment %} Конец футера {% endcomment %}

<script type="text/javascript" src={% static "js/bootstrap.bundle.min.js" %}></script>
</body>
</html>